CREATE TABLE USUARIOS(
	ID_USUARIO INT PRIMARY KEY NOT NULL auto_increment,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(50),
    PASSW VARCHAR(60),
    ROL ENUM('admin_general', 'admin', 'usuario')
);
	
CREATE TABLE UNIVERSIDADES(
	ID_UNIVERSIDAD INT PRIMARY KEY NOT NULL auto_increment,
    NOMBRE_UNIVERSIDAD VARCHAR(100),
    UBICACION VARCHAR(150)
);

CREATE TABLE CARRERAS(
	ID_CARRERA INT PRIMARY KEY NOT NULL auto_increment,
    NOMBRE_CARRERA VARCHAR(100)
);

CREATE TABLE UNIVERSIDADES_CARRERAS(
	ID_UNIVERSIDAD INT,
    ID_CARRERA INT
);


-- PARA QUE NO SE REPITAN
ALTER TABLE UNIVERSIDADES_CARRERAS
ADD CONSTRAINT PK_UNIVERSIDADES_CARRERAS PRIMARY KEY (ID_UNIVERSIDAD, ID_CARRERA);

ALTER TABLE UNIVERSIDADES_CARRERAS
ADD CONSTRAINT FK_UNIVERSIDADES_CARRERAS_UNIVERSIDADES
FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDADES(ID_UNIVERSIDAD);

ALTER TABLE UNIVERSIDADES_CARRERAS
ADD CONSTRAINT FK_UNIVERSIDADES_CARRERAS_CARRERAS
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERAS(ID_CARRERA);
